packages:
  - apps/*
  - packages/*

catalog:
  '@auth/prisma-adapter': ^2.7.6
  '@chromatic-com/storybook': 3.2.2
  '@commitlint/cli': ^19.8.1
  '@commitlint/config-conventional': ^19.8.1
  '@emotion/cache': ^11.14.0
  '@eslint/js': ^9.37.0
  '@fastify/cors': ^10.0.2
  '@fastify/helmet': ^12.0.1
  '@fastify/rate-limit': ^10.1.1
  '@hookform/resolvers': ^3.10.0
  '@next/eslint-plugin-next': ^15.5.5
  '@playwright/test': ^1.48.2
  '@prisma/client': 6.18.0
  '@radix-ui/react-checkbox': ^1.1.2
  '@radix-ui/react-icons': ^1.3.2
  '@radix-ui/react-radio-group': ^1.2.1
  '@storybook/addon-essentials': 8.4.2
  '@storybook/addon-interactions': 8.4.2
  '@storybook/addon-onboarding': 8.4.2
  '@storybook/blocks': 8.4.2
  '@storybook/nextjs': 8.4.2
  '@storybook/react': 8.4.2
  '@storybook/test': 8.4.2
  '@tanstack/react-query': ^5.59.16
  '@tanstack/react-query-devtools': ^5.59.16
  '@tanstack/react-table': ^8.21.3
  '@testing-library/jest-dom': ^6.9.1
  '@testing-library/react': ^16.3.0
  '@testing-library/user-event': ^14.6.1
  '@tiptap/core': ^3.7.0
  '@tiptap/extension-color': ^3.7.0
  '@tiptap/extension-dropcursor': ^3.7.0
  '@tiptap/extension-heading': ^3.7.0
  '@tiptap/extension-image': ^3.7.0
  '@tiptap/extension-list-item': ^3.7.0
  '@tiptap/extension-paragraph': ^3.7.0
  '@tiptap/extension-text-align': ^3.7.0
  '@tiptap/extension-text-style': ^3.7.0
  '@tiptap/pm': ^3.7.0
  '@tiptap/react': ^3.7.0
  '@tiptap/starter-kit': ^3.7.0
  '@types/bcryptjs': ^2.4.6
  '@types/eslint': 8.56.10
  '@types/node': ^22.18.10
  '@types/react': ^19.2.2
  '@types/react-dom': ^19.2.2
  '@vitejs/plugin-react': ^5.0.4
  '@vitest/coverage-istanbul': ^3.2.4
  bcryptjs: ^2.4.3
  chromatic: ^11.3.0
  clsx: ^2.1.1
  commitizen: ^4.3.1
  cz-conventional-changelog: ^3.3.0
  date-fns: ^4.1.0
  eslint: ^9.37.0
  eslint-config-next: 15.5.5
  eslint-config-prettier: ^10.1.8
  eslint-plugin-only-warn: ^1.1.0
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^7.0.0
  eslint-plugin-react-refresh: ^0.4.24
  eslint-plugin-storybook: ^0.11.1
  eslint-plugin-turbo: ^2.5.8
  fastify: ^5.2.0
  framer-motion: ^11.15.0
  globals: ^16.3.0
  husky: ^9.1.7
  jsdom: ^27.0.0
  lint-staged: ^15.5.2
  lucide-react: ^0.545.0
  next: ^15.5.5
  next-auth: ^5.0.0-beta.26
  next-intl: ^3.26.3
  pino: ^10.0.0
  pino-pretty: ^14.0.4
  prettier: ^3.6.2
  prettier-plugin-tailwindcss: ^0.6.14
  prisma: 6.18.0
  radix-ui: ^1.4.3
  react: ^19.2.0
  react-dom: ^19.2.0
  react-hook-form: ^7.54.2
  react-image-crop: ^11.0.10
  react-native-web: ^0.19.13
  storybook: 8.4.2
  tailwindcss: ^3.4.13
  tsup: ^8.5.0
  tsx: ^4.19.2
  turbo: ^2.5.8
  typescript: ^5.9.3
  typescript-eslint: ^8.46.1
  vitest: ^3.2.4
  zod: ^3.24.1

catalogs:
  emotion:
    '@emotion/react': ^11.14.0
    '@emotion/styled': ^11.14.1
  expo:
    '@react-native-async-storage/async-storage': ^2.1.0
    '@react-navigation/native': ^7.0.13
    '@testing-library/react-native': ^12.9.0
    '@types/jest': ^29.5.12
    '@types/react': ^19.1.0
    expo: ~54.0.0
    expo-constants: ~18.0.0
    expo-font: ~14.0.0
    expo-linking: ~8.0.0
    expo-router: ~5.0.0
    expo-splash-screen: ~0.30.0
    expo-status-bar: ~2.0.0
    expo-system-ui: ~5.0.0
    jest: ^29.7.0
    jest-expo: ~54.0.0
    react: ^19.1.0
    react-native: 0.81.0
    react-native-reanimated: ~3.17.0
    react-native-safe-area-context: 5.0.0
    react-native-screens: ~4.5.0
    react-test-renderer: ^19.1.0
  next15:
    '@types/react': ^19.2.2
    '@types/react-dom': ^19.2.2
    next: ^15.5.5
    react: ^19.2.0
    react-dom: ^19.2.0
  react18:
    '@types/react': ^18.3.11
    '@types/react-dom': ^18.3.0
    react: ^18.3.1
    react-dom: ^18.3.1

ignoredBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - prisma
