packages:
  - apps/*
  - packages/*

catalog:
  '@chromatic-com/storybook': 3.2.2
  '@commitlint/cli': ^19.8.1
  '@commitlint/config-conventional': ^19.8.1
  '@emotion/cache': ^11.14.0
  '@eslint/js': ^9.34.0
  '@next/eslint-plugin-next': ^15.5.0
  '@radix-ui/react-checkbox': ^1.1.2
  '@radix-ui/react-icons': ^1.3.2
  '@radix-ui/react-radio-group': ^1.2.1
  '@storybook/addon-essentials': 8.4.2
  '@storybook/addon-interactions': 8.4.2
  '@storybook/addon-onboarding': 8.4.2
  '@storybook/blocks': 8.4.2
  '@storybook/nextjs': 8.4.2
  '@storybook/react': 8.4.2
  '@storybook/test': 8.4.2
  '@tanstack/react-query': ^5.59.16
  '@tanstack/react-query-devtools': ^5.59.16
  '@tanstack/react-table': ^8.21.3
  '@testing-library/jest-dom': ^6.9.1
  '@testing-library/react': ^16.3.0
  '@testing-library/user-event': ^14.6.1
  '@tiptap/core': ^2.26.3
  '@tiptap/extension-color': ^2.26.3
  '@tiptap/extension-dropcursor': ^2.26.3
  '@tiptap/extension-heading': ^2.26.3
  '@tiptap/extension-image': ^2.26.3
  '@tiptap/extension-list-item': ^2.26.3
  '@tiptap/extension-paragraph': ^2.26.3
  '@tiptap/extension-text-align': ^2.26.3
  '@tiptap/extension-text-style': ^2.26.3
  '@tiptap/pm': ^2.26.3
  '@tiptap/react': ^2.26.3
  '@tiptap/starter-kit': ^2.26.3
  '@types/eslint': 8.56.10
  '@types/node': ^22.18.10
  '@types/react': ^19.2.2
  '@types/react-dom': ^19.2.2
  '@vitejs/plugin-react': ^5.0.4
  '@vitest/coverage-istanbul': ^3.2.4
  chromatic: ^11.3.0
  clsx: ^2.1.1
  commitizen: ^4.3.1
  cz-conventional-changelog: ^3.3.0
  date-fns: ^4.1.0
  eslint: ^9.37.0
  eslint-config-next: 15.0.3
  eslint-config-prettier: ^10.1.1
  eslint-plugin-only-warn: ^1.1.0
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^7.0.0
  eslint-plugin-react-refresh: ^0.4.23
  eslint-plugin-storybook: ^0.11.1
  eslint-plugin-turbo: ^2.5.0
  globals: ^16.3.0
  husky: ^9.1.7
  jsdom: ^27.0.0
  lint-staged: ^15.5.2
  lucide-react: ^0.545.0
  next: ^15.5.0
  prettier: ^3.6.2
  prettier-plugin-tailwindcss: ^0.6.14
  radix-ui: ^1.4.3
  react: ^19.1.0
  react-dom: ^19.1.0
  react-image-crop: ^11.0.10
  storybook: 8.4.2
  tailwindcss: ^3.4.13
  tsup: ^8.5.0
  turbo: ^2.5.8
  typescript: ^5.9.3
  typescript-eslint: ^8.40.0
  vitest: ^3.2.4

catalogs:
  emotion:
    '@emotion/react': ^11.14.0
    '@emotion/styled': ^11.14.1
  next14:
    '@types/react': ^18.3.11
    '@types/react-dom': ^18.3.0
    next: ^14.2.6
    react: ^18.3.1
    react-dom: ^18.3.1
  next15:
    '@types/react': ^18.3.11
    '@types/react-dom': ^18.3.0
    next: ^15.0.3
    react: ^19.0.0-rc-66855b96-20241106
    react-dom: ^19.0.0-rc-66855b96-20241106
  react18:
    '@types/react': ^18.3.11
    '@types/react-dom': ^18.3.0
    react: ^18.3.1
    react-dom: ^18.3.1
