/**
 * Shared database enums from Prisma
 *
 * Re-exports enums generated by Prisma Client for use across all apps.
 * This provides a single source of truth for enum values.
 *
 * @example
 * import { UserRole, SubscriptionStatus } from '@eventure/database/enums';
 *
 * if (user.role === UserRole.ADMIN) {
 *   // Admin-only logic
 * }
 */

// Re-export Prisma enums
export { UserRole, SubscriptionStatus, GroupMemberRole, MembershipStatus } from '@prisma/client';

/**
 * UserRole enum values:
 * - ATTENDEE: Regular user who joins groups and events
 * - ORGANIZER: Creates and manages groups/events (Free or Premium)
 * - MODERATOR: Assists organizers with group management (Premium feature)
 * - ADMIN: Full system access
 */

/**
 * SubscriptionStatus enum values:
 * - FREE: Free plan with limitations
 * - PREMIUM: Paid plan with all features
 * - TRIAL: Trial period
 * - CANCELED: Canceled subscription
 */

/**
 * GroupMemberRole enum values:
 * - MEMBER: Regular group member
 * - MODERATOR: Group moderator
 * - ADMIN: Group admin
 */

/**
 * MembershipStatus enum values:
 * - Values depend on Prisma schema
 */
