name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: '[Feature]: '
labels: ['enhancement', 'needs-triage']
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the form below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: "I'm frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: 'I would like to...'
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe alternatives you've considered
      placeholder: "I've also thought about..."

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this feature affect?
      options:
        - Authentication
        - Booking System
        - Cafe Management
        - User Dashboard
        - Owner Dashboard
        - Notifications
        - Database/Prisma
        - UI Components (@tavia/core)
        - API Routes
        - Mobile App (Future)
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (needed for MVP)
        - High (very important)
        - Medium (nice to have)
        - Low (future consideration)
    validations:
      required: true

  - type: dropdown
    id: user_type
    attributes:
      label: User Type
      description: Which user type would benefit from this feature?
      multiple: true
      options:
        - Client (booking user)
        - Owner (cafe/restaurant owner)
        - Admin
        - All users
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups or Examples
      description: If applicable, add mockups, wireframes, or examples from other apps
      placeholder: Add images or links here

  - type: textarea
    id: technical
    attributes:
      label: Technical Considerations
      description: Any technical details or implementation ideas?
      placeholder: 'This could be implemented using...'

  - type: checkboxes
    id: breaking
    attributes:
      label: Breaking Changes
      description: Would this feature introduce breaking changes?
      options:
        - label: This feature would require breaking changes
        - label: This feature is backward compatible

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the feature request here
