import type { QuizQuestion } from '../_types';

export const QUIZ_QUESTIONS: QuizQuestion[] = [
  {
    id: 'q1-mindset',
    step: 1,
    type: 'multiple-choice',
    question: 'When you think about money, how do you feel?',
    description: 'Be honest — there are no wrong answers.',
    required: true,
    options: [
      { id: 'avoid', label: 'I avoid thinking about it', value: 'avoid', points: 1 },
      { id: 'stressed', label: 'Stressed but trying', value: 'stressed', points: 2 },
      { id: 'confident', label: 'Confident in my basics', value: 'confident', points: 3 },
      { id: 'excited', label: 'Excited to grow and optimize', value: 'excited', points: 4 },
    ],
  },
  {
    id: 'q2-frequency',
    step: 2,
    type: 'multiple-choice',
    question: 'How often do you review your finances?',
    required: true,
    options: [
      { id: 'rarely', label: 'Rarely or never', value: 'rarely', points: 1 },
      { id: 'sometimes', label: 'Every few months', value: 'sometimes', points: 2 },
      { id: 'monthly', label: 'Monthly', value: 'monthly', points: 3 },
      { id: 'weekly', label: 'Weekly or more', value: 'weekly', points: 4 },
    ],
  },
  {
    id: 'q3-confidence',
    step: 3,
    type: 'multiple-choice',
    question: 'Rate your confidence in managing money (1 = no clue, 4 = very confident)',
    required: true,
    options: [
      { id: 'lost', label: "I'm totally lost", value: 'lost', points: 1 },
      { id: 'learning', label: 'Learning the basics', value: 'learning', points: 2 },
      { id: 'comfortable', label: 'Pretty comfortable', value: 'comfortable', points: 3 },
      { id: 'advanced', label: 'Advanced — I optimize', value: 'advanced', points: 4 },
    ],
  },
  {
    id: 'q4-savings',
    step: 4,
    type: 'multiple-choice',
    question: 'Do you save money consistently?',
    required: true,
    options: [
      { id: 'no-savings', label: 'Not yet', value: 'no-savings', points: 1 },
      { id: 'trying', label: 'Trying, but inconsistent', value: 'trying', points: 2 },
      { id: 'yes-small', label: 'Yes, a small amount monthly', value: 'yes-small', points: 3 },
      {
        id: 'yes-automated',
        label: 'Yes, automated and optimized',
        value: 'yes-automated',
        points: 4,
      },
    ],
  },
  {
    id: 'q5-goal',
    step: 5,
    type: 'multiple-choice',
    question: "What's your biggest financial goal right now?",
    required: true,
    options: [
      { id: 'basics', label: 'Understanding the basics', value: 'basics', points: 1 },
      { id: 'emergency', label: 'Building an emergency fund', value: 'emergency', points: 2 },
      { id: 'invest', label: 'Start investing', value: 'invest', points: 3 },
      { id: 'wealth', label: 'Growing wealth and passive income', value: 'wealth', points: 4 },
    ],
  },
  {
    id: 'q6-emotion',
    step: 6,
    type: 'multiple-choice',
    question: 'How do you feel about your financial future?',
    required: true,
    options: [
      { id: 'anxious', label: 'Anxious and uncertain', value: 'anxious', points: 1 },
      { id: 'hopeful', label: 'Hopeful but need direction', value: 'hopeful', points: 2 },
      { id: 'optimistic', label: 'Optimistic with a plan', value: 'optimistic', points: 3 },
      { id: 'in-control', label: 'In control and scaling', value: 'in-control', points: 4 },
    ],
  },
  {
    id: 'q7-reflection',
    step: 7,
    type: 'text',
    question: "In one sentence, what's stopping you from reaching your financial goals?",
    description: 'E.g., "I don\'t know where to start", "No time", "Lack of discipline"',
    required: true,
    placeholder: 'Type your answer...',
  },
  {
    id: 'q8-learning',
    step: 8,
    type: 'multiple-choice',
    question: 'How do you prefer to learn?',
    required: true,
    options: [
      { id: 'guided', label: 'Step-by-step guidance', value: 'guided', points: 1 },
      { id: 'courses', label: 'Short courses', value: 'courses', points: 2 },
      { id: 'community', label: 'Community + accountability', value: 'community', points: 3 },
      { id: 'self-driven', label: 'Self-driven with tools', value: 'self-driven', points: 4 },
    ],
  },
  {
    id: 'q9-commitment',
    step: 9,
    type: 'scale',
    question: 'How much time can you realistically dedicate each week to improving your finances?',
    description: 'Be honest with yourself.',
    required: true,
    scaleMin: 0,
    scaleMax: 4,
    scaleLabels: {
      min: '0 hours',
      max: '4+ hours',
    },
  },
  {
    id: 'q10-success',
    step: 10,
    type: 'text',
    question: 'What does "financial success" mean to you personally?',
    description: "There's no right answer — just yours (max 150 characters).",
    required: true,
    placeholder: 'e.g., Not worrying about bills, having freedom to travel...',
  },
];

export const TOTAL_STEPS = QUIZ_QUESTIONS.length;
